export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGIN_ERROR_REMOVE = "LOGIN_ERROR_REMOVE"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_ERROR = "REGISTER_ERROR"
export const REGISTER_ERROR_REMOVE = "REGISTER_ERROR_REMOVE"

export const MAIN_TYPE = "MAIN_TYPE"
export const CROPS_LIST = "CROPS_LIST"
export const CHEMICALS_LIST = "CHEMICALS_LIST"

export const CROP_DETAIL = "CROP_DETAIL"
export const CROP_ADD = "CROP_ADD"
export const CHEMICAL_DETAIL = "CHEMICAL_DETAIL"

export const MY_CROP_DETAIL = "MY_CROP_DETAIL"


export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"

export const CHANGE_PASSWORD = "CHANGE_PASSWORD"
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR"